
library(dplyr)
library(reshape2)
library(data.table)
library(RODBC)
library(stringr)
library(ggplot2)
library(ggthemes)
library(data.table)
library(readr)
library(xlsx)
library(gridExtra)
library(Hmisc)
library(psych)
library(e1071)
library(caret)
library(glmnet)
library(nnet)
library(mlbench)
library(randomForest)
library(plotROC)
library(ROCR)
library(tidyr)
library(signal)
library(pROC)
library(gdata)

setwd("D:/College/Proposal 2/R/Thesis")
source('Functions.R')
source('Data Re-shape and cleanse.R')

source('1.1 Engineering model.R')
source('2. SVM model Engineering features.R')
source('2. SVM model.R')
source('3. Regression Momentum Data.R')
source('3. Regression.R')


